### ISSUE TITLE
Prebuilt docker image

### ISSUE THREAD

**Issue by kimdre** [AnderssonPeter/cloud-init-linter#1]
Hi, could you specify a pre-built docker image for the action?
Every time the action runs it needs to be built for ~20 seconds for every run which sums up after a while.

**Comment by AnderssonPeter** [comment]
I'm willing but have no idea how to, could you provide some relevant documentation?

**Comment by kimdre** [comment]
I haven't developed any actions myself yet but maybe this could solve it?
https://github.com/marketplace/actions/push-pre-built-javascript-typescript-docker-container-github-action

**Comment by kimdre** [comment]
Otherwise if you know that actions can be pre-built I can write you a pull request with the workflow to build the image automatically after publishing a new release/tag

**Comment by AnderssonPeter** [comment]
> Otherwise if you know that actions can be pre-built I can write you a pull request with the workflow to build the image automatically after publishing a new release/tag

That would be great, my PC time is currently limited so this would be nice.

**Comment by kimdre** [comment]
Ok, so I played around a bit with the actions [in my fork ](https://github.com/kimdre/cloud-init-linter) and unfortunately it seems you can't sepcify a docker image in the `uses:` setting.
As a workaround you could use the `run:` step to execute the pre-built image like so:

```yaml
jobs:
  linter:
    name: Validate Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Lint cloud-init
        run: docker run --rm --v "$pwd":/ ghcr.io/kimdre/cloud-init-linter:v1 
```

I'm not really happy with this approach though.
